version: "3"

services:
  # PostgreSQL
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD", "nc", "-z -v", "0.0.0.0 5432"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Web
  web:
    build: .
    entrypoint: ["./entrypoint.sh"]
    command: python3 manage.py runserver 0.0.0.0:8000 --settings devhub.settings.docker
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
